export const data = [
  {
    sNo: 1,
    title: 'Freedom',
    logLine: 'Adam dont know nothing',
    theme: 'kkkk',
    genre: 'Action Adventure, None',
    timeLine: 'now',
  },
  {
    sNo: 2,
    title: 'Freedom',
    logLine: 'Adam dont know nothing',
    theme: 'kkkk',
    genre: 'Action Adventure, None',
    timeLine: 'old',
  },
  {
    sNo: 3,
    title: 'Freedom',
    logLine: 'Adam dont know nothing',
    theme: 'kkkk',
    genre: 'Action Adventure, None',
    timeLine: 'old',
  },
  {
    sNo: 4,
    title: 'Freedom',
    logLine: 'Adam dont know nothing',
    theme: 'kkkk',
    genre: 'Action Adventure, None',
    timeLine: 'now',
  },
  {
    sNo: 5,
    title: 'Freedom',
    logLine: 'Adam dont know nothing',
    theme: 'kkkk',
    genre: 'Action Adventure, None',
    timeLine: 'old',
  },
  {
    sNo: 6,
    title: 'Freedom',
    logLine: 'Adam dont know nothing',
    theme: 'kkkk',
    genre: 'Action Adventure, None',
    timeLine: 'now',
  },
  {
    sNo: 7,
    title: 'Freedom',
    logLine: 'Adam dont know nothing',
    theme: 'kkkk',
    genre: 'Action Adventure, None',
    timeLine: 'old',
  },
  {
    sNo: 8,
    title: 'Freedom',
    logLine: 'Adam dont know nothing',
    theme: 'kkkk',
    genre: 'Action Adventure, None',
    timeLine: 'old',
  },
];
